[boards]
boards_dir=boards

[env:esp32-s3-devkitc-1]
platform = espressif32
board = freenove_s3_devkit
;board_build.partitions = 8MB_no_ota.csv
framework = arduino
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
 -DNO_LCD_PANEL_API
 ;-DUSE_SPI_MASTER
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
upload_speed = 921600
upload_port = COM23
monitor_port = COM23
lib_deps = SPIFFS
    FS
    codewitch-honey-crisis/htcw_uix
    codewitch-honey-crisis/htcw_sfx